spring:
  application:
    name: Hotels
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/hotels
    username: sa
    password: password
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
springdoc:
  default-produces-media-type: application/json
  override-with-generic-response: false
server:
  port: 8092
  servlet:
    context-path: /property-view